services:
  etl-job:
    build: ./backend
    volumes:
      - ./backend:/data_docker  # <-- mounting volume
    environment:
      - TAJNE_HASLO=${APP_SECRET}
      - SRODOWISKO=${ENV_TYPE}
      - DB_HOST=warehouse
      - DB_USER=postgres
      - DB_PASS=${POSTGRES_PASS}
      - DB_NAME=postgres
    working_dir: /data_docker 
    command: python main.py
    depends_on:
      - warehouse

  warehouse:
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
